import { int, mysqlEnum, mysqlTable, text, timestamp, varchar } from "drizzle-orm/mysql-core";

export const users = mysqlTable("users", {
  id: int("id").autoincrement().primaryKey(), openId: varchar("openId", { length: 64 }).notNull().unique(), name: text("name"), email: varchar("email", { length: 320 }), loginMethod: varchar("loginMethod", { length: 64 }), role: mysqlEnum("role", ["user", "admin"]).default("user").notNull(), createdAt: timestamp("createdAt").defaultNow().notNull(), updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(), lastSignedIn: timestamp("lastSignedIn").defaultNow().notNull(),
});
export const memories = mysqlTable("memories", {
  id: int("id").autoincrement().primaryKey(), userId: int("userId").notNull(), category: varchar("category", { length: 64 }).notNull(), content: text("content").notNull(), confidence: int("confidence").default(80).notNull(), createdAt: timestamp("createdAt").defaultNow().notNull(), updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});
export const tasks = mysqlTable("tasks", {
  id: int("id").autoincrement().primaryKey(), userId: int("userId").notNull(), goal: text("goal").notNull(), messages: text("messages").notNull(), status: mysqlEnum("status", ["queued", "planning", "running", "waiting_approval", "paused", "failed", "completed", "cancelled", "dead_letter"]).default("queued").notNull(), progress: int("progress").default(0).notNull(), retries: int("retries").default(0).notNull(), attemptCount: int("attemptCount").default(0).notNull(), maxAttempts: int("maxAttempts").default(3).notNull(), lastError: text("lastError"), result: text("result"), idempotencyKey: varchar("idempotencyKey", { length: 160 }), workerId: varchar("workerId", { length: 100 }), lockedAt: timestamp("lockedAt"), heartbeatAt: timestamp("heartbeatAt"), leaseTimeout: int("leaseTimeout").default(60).notNull(), nextRetryAt: timestamp("nextRetryAt"), createdAt: timestamp("createdAt").defaultNow().notNull(), updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(), completedAt: timestamp("completedAt"),
});
export const taskEvents = mysqlTable("taskEvents", { id: int("id").autoincrement().primaryKey(), taskId: int("taskId").notNull(), type: varchar("type", { length: 64 }).notNull(), message: text("message").notNull(), metadata: text("metadata"), createdAt: timestamp("createdAt").defaultNow().notNull() });
export const approvals = mysqlTable("approvals", { id: int("id").autoincrement().primaryKey(), taskId: int("taskId").notNull(), userId: int("userId").notNull(), toolName: varchar("toolName", { length: 120 }).notNull(), action: varchar("action", { length: 40 }).notNull(), riskLevel: varchar("riskLevel", { length: 24 }).default("high").notNull(), requiredPermission: varchar("requiredPermission", { length: 160 }), resourceScope: varchar("resourceScope", { length: 300 }), status: mysqlEnum("status", ["pending", "approved", "rejected"]).default("pending").notNull(), createdAt: timestamp("createdAt").defaultNow().notNull(), resolvedAt: timestamp("resolvedAt") });
export const googleConnections = mysqlTable("googleConnections", { id: int("id").autoincrement().primaryKey(), userId: int("userId").notNull().unique(), encryptedAccessToken: text("encryptedAccessToken").notNull(), encryptedRefreshToken: text("encryptedRefreshToken"), expiresAt: timestamp("expiresAt"), scopes: text("scopes").notNull(), createdAt: timestamp("createdAt").defaultNow().notNull(), updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull() });
export const googleOAuthStates = mysqlTable("googleOAuthStates", { id: int("id").autoincrement().primaryKey(), state: varchar("state", { length: 180 }).notNull().unique(), userId: int("userId").notNull(), redirectUri: varchar("redirectUri", { length: 500 }).notNull(), expiresAt: timestamp("expiresAt").notNull(), createdAt: timestamp("createdAt").defaultNow().notNull() });
export const integrationSecrets = mysqlTable("integrationSecrets", { id: int("id").autoincrement().primaryKey(), provider: varchar("provider", { length: 60 }).notNull().unique(), encryptedClientId: text("encryptedClientId").notNull(), encryptedClientSecret: text("encryptedClientSecret").notNull(), updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(), createdAt: timestamp("createdAt").defaultNow().notNull() });
export type User = typeof users.$inferSelect; export type InsertUser = typeof users.$inferInsert; export type Memory = typeof memories.$inferSelect; export type InsertMemory = typeof memories.$inferInsert; export type Task = typeof tasks.$inferSelect; export type InsertTask = typeof tasks.$inferInsert; export type TaskEvent = typeof taskEvents.$inferSelect; export type InsertTaskEvent = typeof taskEvents.$inferInsert; export type Approval = typeof approvals.$inferSelect;
