import { useState } from "react";
import { CheckCircle2, Eye, EyeOff, KeyRound, ShieldCheck } from "lucide-react";
import { Link } from "wouter";
import { useAuth } from "@/_core/hooks/useAuth";
import { Button } from "@/components/ui/button";
import { trpc } from "@/lib/trpc";

export default function Settings() {
  const { user, loading } = useAuth();
  const status = trpc.integrations.googleStatus.useQuery(undefined, { enabled: user?.role === "admin" });
  const save = trpc.integrations.saveGoogle.useMutation({ onSuccess: () => { setMessage("تم حفظ بيانات Google مشفّرة على الخادم."); setSecret(""); void status.refetch(); } });
  const [clientId, setClientId] = useState("");
  const [secret, setSecret] = useState("");
  const [showSecret, setShowSecret] = useState(false);
  const [message, setMessage] = useState("");
  if (loading) return <div className="settings-page"><div className="settings-card">جارٍ التحقق من الصلاحيات…</div></div>;
  if (!user) return <div className="settings-page"><div className="settings-card"><KeyRound size={28} /><h1>تسجيل الدخول مطلوب</h1><p>سجّلي الدخول للوصول إلى إعدادات التكاملات.</p></div></div>;
  if (user.role !== "admin") return <div className="settings-page"><div className="settings-card"><ShieldCheck size={28} /><h1>إعدادات محمية</h1><p>إدخال أسرار OAuth متاح لمالك مساحة العمل أو المشرف فقط.</p><Link href="/"><Button variant="outline">العودة إلى NOVA</Button></Link></div></div>;
  return <div className="settings-page" dir="rtl"><div className="settings-top"><Link href="/" className="settings-back">← العودة إلى NOVA</Link><p className="eyebrow">WORKSPACE SETTINGS</p><h1>التكاملات</h1><p>خدمات Google المجانية للاستخدام الشخصي: تقويم، Drive، وSheets بصلاحيات قراءة أولًا.</p></div><section className="settings-card integration-card"><div className="integration-heading"><div className="google-logo">G</div><div><h2>Google Workspace</h2><p>Calendar · Drive · Sheets · OAuth</p></div><span className={status.data?.configured ? "connected-pill" : "offline-pill"}>{status.data?.configured ? <><CheckCircle2 size={13} /> مهيأ</> : "غير مهيأ"}</span></div><div className="google-services"><div><b>Calendar</b><span>المواعيد وFree/Busy؛ الكتابة تتطلب موافقة.</span></div><div><b>Drive</b><span>البحث وقراءة الملفات النصية وGoogle Docs حتى 2 MB.</span></div><div><b>Sheets</b><span>قراءة نطاقات الخلايا للتحليل والتلخيص.</span></div></div><div className="security-note"><ShieldCheck size={17} /><span>Client Secret يُرسل مباشرة إلى الخادم عبر tRPC محمي، ويُخزن بتشفير AES-256-GCM. لا نعرضه بعد الحفظ. بعد إضافة نطاقات جديدة، أعد ربط Google للموافقة عليها.</span></div><label>Google OAuth Client ID<input value={clientId} onChange={event => setClientId(event.target.value)} placeholder="1234567890-…apps.googleusercontent.com" autoComplete="off" /></label><label>Google OAuth Client Secret<div className="secret-input"><input type={showSecret ? "text" : "password"} value={secret} onChange={event => setSecret(event.target.value)} placeholder="أدخل السر من Google Cloud Console" autoComplete="new-password" /><button type="button" onClick={() => setShowSecret(value => !value)} aria-label={showSecret ? "إخفاء السر" : "إظهار السر"}>{showSecret ? <EyeOff size={16} /> : <Eye size={16} />}</button></div></label><p className="redirect-hint">Redirect URI المطلوب في Google Cloud Console:<code>{window.location.origin}/api/google/callback</code></p><p className="redirect-hint">Google Cloud APIs: فعّل Calendar API وDrive API وSheets API، ثم استخدم OAuth scopes للقراءة فقط.</p><div className="settings-actions"><Button disabled={!clientId.trim() || !secret.trim() || save.isPending} onClick={() => { setMessage(""); save.mutate({ clientId: clientId.trim(), clientSecret: secret.trim() }); }}>{save.isPending ? "جارٍ الحفظ…" : "حفظ بيانات Google"}</Button>{status.data?.configured && <a className="google-connect-button" href={`/api/google/connect?origin=${encodeURIComponent(window.location.origin)}`}>ربط حساب Google</a>}{message && <span className="save-message"><CheckCircle2 size={14} />{message}</span>}</div>{save.error && <p className="form-error">تعذر الحفظ: {save.error.message}</p>}</section></div>;
}
