import { createCipheriv, createDecipheriv, createHash, randomBytes, randomUUID } from "node:crypto";
import { and, eq, gt } from "drizzle-orm";
import { approvals, googleConnections, googleOAuthStates, integrationSecrets } from "../drizzle/schema";
import { getDb } from "./db";
import { ENV } from "./_core/env";

export const GOOGLE_SCOPES = ["https://www.googleapis.com/auth/calendar.readonly", "https://www.googleapis.com/auth/calendar.events", "https://www.googleapis.com/auth/drive.readonly", "https://www.googleapis.com/auth/spreadsheets.readonly"];
export const CALENDAR_PERMISSIONS = { list: "calendar.read", get: "calendar.read", search: "calendar.read", freebusy: "calendar.read", create: "calendar.create", update: "calendar.update", delete: "calendar.delete" } as const;
export const GOOGLE_SERVICE_PERMISSIONS = { driveSearch: "drive.read", driveRead: "drive.read", sheetsRead: "sheets.read" } as const;
const GOOGLE_TOKEN_URL = "https://oauth2.googleapis.com/token";
const CALENDAR_API = "https://www.googleapis.com/calendar/v3";
const DRIVE_API = "https://www.googleapis.com/drive/v3";
const SHEETS_API = "https://sheets.googleapis.com/v4";

function key() { return createHash("sha256").update(ENV.cookieSecret || "nova-calendar-development-key").digest(); }
function encrypt(value: string) { const iv = randomBytes(12); const cipher = createCipheriv("aes-256-gcm", key(), iv); const encrypted = Buffer.concat([cipher.update(value, "utf8"), cipher.final()]); return `${iv.toString("base64url")}.${cipher.getAuthTag().toString("base64url")}.${encrypted.toString("base64url")}`; }
function decrypt(value: string) { const [iv, tag, ciphertext] = value.split("."); const decipher = createDecipheriv("aes-256-gcm", key(), Buffer.from(iv, "base64url")); decipher.setAuthTag(Buffer.from(tag, "base64url")); return Buffer.concat([decipher.update(Buffer.from(ciphertext, "base64url")), decipher.final()]).toString("utf8"); }
async function credentials() { const db = await getDb(); const row = db ? (await db.select().from(integrationSecrets).where(eq(integrationSecrets.provider, "google")).limit(1))[0] : undefined; return row ? { clientId: decrypt(row.encryptedClientId), clientSecret: decrypt(row.encryptedClientSecret) } : { clientId: process.env.GOOGLE_CLIENT_ID ?? "", clientSecret: process.env.GOOGLE_CLIENT_SECRET ?? "" }; }
async function requireCredentials() { const value = await credentials(); if (!value.clientId || !value.clientSecret) throw new Error("Google Calendar is not configured: add credentials in Settings → Integrations"); return value; }

export async function createGoogleAuthorizationUrl(input: { userId: number; origin: string }) {
  const google = await requireCredentials();
  const origin = new URL(input.origin); if (!/^https?:$/.test(origin.protocol)) throw new Error("Invalid frontend origin");
  const redirectUri = `${origin.origin}/api/google/callback`; const state = randomUUID(); const db = await getDb();
  if (!db) throw new Error("Database is required for OAuth state");
  await db.insert(googleOAuthStates).values({ state, userId: input.userId, redirectUri, expiresAt: new Date(Date.now() + 10 * 60_000) });
  const query = new URLSearchParams({ client_id: google.clientId, redirect_uri: redirectUri, response_type: "code", access_type: "offline", prompt: "consent", scope: GOOGLE_SCOPES.join(" "), state });
  return `https://accounts.google.com/o/oauth2/v2/auth?${query.toString()}`;
}

export async function completeGoogleAuthorization(input: { code: string; state: string }) {
  const google = await requireCredentials(); const db = await getDb(); if (!db) throw new Error("Database is required for OAuth callback");
  const row = (await db.select().from(googleOAuthStates).where(and(eq(googleOAuthStates.state, input.state), gt(googleOAuthStates.expiresAt, new Date()))).limit(1))[0];
  if (!row) throw new Error("Invalid or expired Google OAuth state");
  const response = await fetch(GOOGLE_TOKEN_URL, { method: "POST", headers: { "Content-Type": "application/x-www-form-urlencoded" }, body: new URLSearchParams({ code: input.code, client_id: google.clientId, client_secret: google.clientSecret, redirect_uri: row.redirectUri, grant_type: "authorization_code" }) });
  if (!response.ok) throw new Error(`Google token exchange failed (${response.status})`);
  const token = await response.json() as { access_token: string; refresh_token?: string; expires_in?: number; scope?: string };
  await db.insert(googleConnections).values({ userId: row.userId, encryptedAccessToken: encrypt(token.access_token), encryptedRefreshToken: token.refresh_token ? encrypt(token.refresh_token) : null, expiresAt: new Date(Date.now() + (token.expires_in ?? 3600) * 1000), scopes: token.scope ?? GOOGLE_SCOPES.join(" ") }).onDuplicateKeyUpdate({ set: { encryptedAccessToken: encrypt(token.access_token), encryptedRefreshToken: token.refresh_token ? encrypt(token.refresh_token) : null, expiresAt: new Date(Date.now() + (token.expires_in ?? 3600) * 1000), scopes: token.scope ?? GOOGLE_SCOPES.join(" ") } });
  await db.delete(googleOAuthStates).where(eq(googleOAuthStates.id, row.id)); return row.redirectUri.replace(/\/api\/google\/callback$/, "/?google=connected");
}

async function accessToken(userId: number) { const google = await requireCredentials(); const db = await getDb(); if (!db) throw new Error("Database unavailable"); const row = (await db.select().from(googleConnections).where(eq(googleConnections.userId, userId)).limit(1))[0]; if (!row) throw new Error("Google Calendar is not connected"); if (row.expiresAt && row.expiresAt.getTime() > Date.now() + 60_000) return decrypt(row.encryptedAccessToken); const refresh = row.encryptedRefreshToken ? decrypt(row.encryptedRefreshToken) : null; if (!refresh) throw new Error("Google refresh token is missing; reconnect Google Calendar"); const response = await fetch(GOOGLE_TOKEN_URL, { method: "POST", headers: { "Content-Type": "application/x-www-form-urlencoded" }, body: new URLSearchParams({ client_id: google.clientId, client_secret: google.clientSecret, refresh_token: refresh, grant_type: "refresh_token" }) }); if (!response.ok) throw new Error(`Google token refresh failed (${response.status})`); const token = await response.json() as { access_token: string; expires_in?: number }; await db.update(googleConnections).set({ encryptedAccessToken: encrypt(token.access_token), expiresAt: new Date(Date.now() + (token.expires_in ?? 3600) * 1000) }).where(eq(googleConnections.id, row.id)); return token.access_token; }
async function calendarFetch<T>(userId: number, path: string, init?: RequestInit) { const token = await accessToken(userId); const response = await fetch(`${CALENDAR_API}${path}`, { ...init, headers: { Authorization: `Bearer ${token}`, "Content-Type": "application/json", ...(init?.headers ?? {}) } }); if (!response.ok) throw new Error(`Google Calendar request failed (${response.status})`); return response.status === 204 ? null as T : await response.json() as T; }
async function googleFetch<T>(userId: number, baseUrl: string, path: string, init?: RequestInit) { const token = await accessToken(userId); const response = await fetch(`${baseUrl}${path}`, { ...init, headers: { Authorization: `Bearer ${token}`, "Content-Type": "application/json", ...(init?.headers ?? {}) } }); if (!response.ok) throw new Error(`Google API request failed (${response.status})`); return response.status === 204 ? null as T : await response.json() as T; }
export async function calendarList(userId: number, params?: { calendarId?: string; timeMin?: string; timeMax?: string }) { const query = new URLSearchParams({ singleEvents: "true", orderBy: "startTime", ...(params?.timeMin ? { timeMin: params.timeMin } : {}), ...(params?.timeMax ? { timeMax: params.timeMax } : {}) }); return calendarFetch(userId, `/calendars/${encodeURIComponent(params?.calendarId ?? "primary")}/events?${query}`); }
export async function calendarGet(userId: number, eventId: string, calendarId = "primary") { return calendarFetch(userId, `/calendars/${encodeURIComponent(calendarId)}/events/${encodeURIComponent(eventId)}`); }
export async function calendarSearch(userId: number, q: string, calendarId = "primary") { return calendarFetch(userId, `/calendars/${encodeURIComponent(calendarId)}/events?singleEvents=true&orderBy=startTime&q=${encodeURIComponent(q)}`); }
export async function calendarFreebusy(userId: number, timeMin: string, timeMax: string, calendarIds = ["primary"]) { return calendarFetch(userId, "/freeBusy", { method: "POST", body: JSON.stringify({ timeMin, timeMax, items: calendarIds.map(id => ({ id })) }) }); }
export async function calendarCreate(userId: number, event: Record<string, unknown>, calendarId = "primary") { return calendarFetch(userId, `/calendars/${encodeURIComponent(calendarId)}/events`, { method: "POST", body: JSON.stringify(event) }); }
export async function calendarUpdate(userId: number, eventId: string, event: Record<string, unknown>, calendarId = "primary") { return calendarFetch(userId, `/calendars/${encodeURIComponent(calendarId)}/events/${encodeURIComponent(eventId)}`, { method: "PUT", body: JSON.stringify(event) }); }
export async function calendarDelete(userId: number, eventId: string, calendarId = "primary") { return calendarFetch(userId, `/calendars/${encodeURIComponent(calendarId)}/events/${encodeURIComponent(eventId)}`, { method: "DELETE" }); }
export type GoogleDriveFile = { id: string; name: string; mimeType: string; modifiedTime?: string; size?: string; webViewLink?: string };
export async function driveSearch(userId: number, query: string, pageSize = 20) { const safe = query.trim().replace(/'/g, "\\'"); const params = new URLSearchParams({ q: `trashed = false and fullText contains '${safe}'`, pageSize: String(Math.min(Math.max(pageSize, 1), 100)), orderBy: "modifiedTime desc", fields: "files(id,name,mimeType,modifiedTime,size,webViewLink),nextPageToken" }); return googleFetch<{ files: GoogleDriveFile[]; nextPageToken?: string }>(userId, DRIVE_API, `/files?${params}`); }
export async function driveList(userId: number, pageSize = 20) { const params = new URLSearchParams({ q: "trashed = false", pageSize: String(Math.min(Math.max(pageSize, 1), 100)), orderBy: "modifiedTime desc", fields: "files(id,name,mimeType,modifiedTime,size,webViewLink),nextPageToken" }); return googleFetch<{ files: GoogleDriveFile[]; nextPageToken?: string }>(userId, DRIVE_API, `/files?${params}`); }
export async function driveGetText(userId: number, fileId: string, mimeType?: string) { const exportType = mimeType === "application/vnd.google-apps.document" ? "text/plain" : mimeType === "application/vnd.google-apps.spreadsheet" ? "text/csv" : mimeType === "application/vnd.google-apps.presentation" ? "text/plain" : undefined; const suffix = exportType ? `/files/${encodeURIComponent(fileId)}/export?mimeType=${encodeURIComponent(exportType)}` : `/files/${encodeURIComponent(fileId)}?alt=media`; const token = await accessToken(userId); const response = await fetch(`${DRIVE_API}${suffix}`, { headers: { Authorization: `Bearer ${token}` } }); if (!response.ok) throw new Error(`Google Drive content request failed (${response.status})`); const text = await response.text(); if (text.length > 2_000_000) throw new Error("Drive file exceeds the safe 2 MB text limit"); return { fileId, mimeType: mimeType ?? "text/plain", content: text };
}
export async function sheetsGetValues(userId: number, spreadsheetId: string, range: string) { const params = new URLSearchParams({ majorDimension: "ROWS", valueRenderOption: "FORMATTED_VALUE" }); return googleFetch<{ range?: string; majorDimension?: string; values?: string[][] }>(userId, SHEETS_API, `/spreadsheets/${encodeURIComponent(spreadsheetId)}/values/${encodeURIComponent(range)}?${params}`); }
export async function googleCalendarConfigured() { const value = await credentials(); return Boolean(value.clientId && value.clientSecret); }
export async function saveGoogleCredentials(input: { clientId: string; clientSecret: string }) { const db = await getDb(); if (!db) throw new Error("Database unavailable"); await db.insert(integrationSecrets).values({ provider: "google", encryptedClientId: encrypt(input.clientId), encryptedClientSecret: encrypt(input.clientSecret) }).onDuplicateKeyUpdate({ set: { encryptedClientId: encrypt(input.clientId), encryptedClientSecret: encrypt(input.clientSecret), updatedAt: new Date() } }); return { configured: true }; }
export async function assertCalendarApproval(input: { approvalId: number; userId: number; permission: string }) { const db = await getDb(); if (!db) throw new Error("Database unavailable"); const row = (await db.select().from(approvals).where(and(eq(approvals.id, input.approvalId), eq(approvals.userId, input.userId), eq(approvals.status, "approved"))).limit(1))[0]; if (!row || row.requiredPermission !== input.permission) throw new Error(`Approved permission required: ${input.permission}`); return true; }
