import { randomUUID } from "node:crypto";
import { EventEmitter } from "node:events";
import { and, desc, eq, inArray, isNull, lte, or } from "drizzle-orm";
import { approvals, taskEvents, tasks } from "../drizzle/schema";
import { getDb } from "./db";
import { AgentMessage, runAgent } from "./agent";

export type TaskStatus = "queued" | "planning" | "running" | "waiting_approval" | "paused" | "failed" | "completed" | "cancelled" | "dead_letter";
export type TaskEvent = { id: string; taskId: number; type: string; message: string; createdAt: string; metadata?: Record<string, unknown> };
export type TaskSnapshot = { id: number; userId: number; goal: string; status: TaskStatus; progress: number; retries: number; attemptCount: number; maxAttempts: number; workerId?: string | null; lockedAt?: string | null; heartbeatAt?: string | null; nextRetryAt?: string | null; lastError?: string | null; result?: string | null; createdAt: string; updatedAt: string };
type MemoryTask = TaskSnapshot & { messages: AgentMessage[]; events: TaskEvent[]; pauseRequested?: boolean; idempotencyKey?: string };

const WORKER_ID = `worker-${randomUUID().slice(0, 8)}`;
const LEASE_MS = 60_000;
const fallbackTasks = new Map<number, MemoryTask>();
const eventBus = new EventEmitter();
let nextId = 1;
let workerActive = false;
let workerTimer: ReturnType<typeof setInterval> | undefined;
let shuttingDown = false;

function now() { return new Date().toISOString(); }
function snapshot(task: MemoryTask): TaskSnapshot { const { messages: _messages, events: _events, pauseRequested: _pause, idempotencyKey: _key, ...value } = task; return value; }
function emit(task: MemoryTask, type: string, message: string, metadata?: Record<string, unknown>) { const event = { id: `${task.id}-${task.events.length + 1}`, taskId: task.id, type, message, createdAt: now(), metadata }; task.events.push(event); eventBus.emit(`task:${task.id}`, event); void persistEvent(event); }
async function persistEvent(event: TaskEvent) { const db = await getDb(); if (db) await db.insert(taskEvents).values({ taskId: event.taskId, type: event.type, message: event.message, metadata: event.metadata ? JSON.stringify(event.metadata) : null }).catch(() => undefined); }
async function updatePersisted(task: MemoryTask) { const db = await getDb(); if (!db) return; await db.update(tasks).set({ status: task.status, progress: task.progress, retries: task.retries, attemptCount: task.attemptCount, workerId: task.workerId ?? null, lockedAt: task.lockedAt ? new Date(task.lockedAt) : null, heartbeatAt: task.heartbeatAt ? new Date(task.heartbeatAt) : null, nextRetryAt: task.nextRetryAt ? new Date(task.nextRetryAt) : null, result: task.result ?? null, lastError: task.lastError ?? null, completedAt: ["completed", "failed", "cancelled", "dead_letter"].includes(task.status) ? new Date() : null }).where(eq(tasks.id, task.id)).catch(() => undefined); }
function isLeaseExpired(task: { lockedAt?: string | null; heartbeatAt?: string | null }) { const stamp = task.heartbeatAt ?? task.lockedAt; return Boolean(stamp && Date.now() - new Date(stamp).getTime() > LEASE_MS); }
function backoff(attempt: number) { return Math.min(300_000, 1000 * 2 ** Math.max(0, attempt - 1)); }
function getMemoryTask(id: number) { return fallbackTasks.get(id); }

async function claim(task: MemoryTask) { if (task.status !== "queued" || task.pauseRequested || (task.nextRetryAt && new Date(task.nextRetryAt).getTime() > Date.now())) return false; task.workerId = WORKER_ID; task.lockedAt = now(); task.heartbeatAt = now(); task.attemptCount += 1; task.nextRetryAt = null; await updatePersisted(task); emit(task, "task.claimed", `استلم العامل ${WORKER_ID} المهمة`, { workerId: WORKER_ID, attempt: task.attemptCount }); return true; }
async function execute(task: MemoryTask) {
  if (!(await claim(task))) return;
  const heartbeat = setInterval(() => { task.heartbeatAt = now(); void updatePersisted(task); }, 10_000);
  try {
    task.status = "planning"; task.progress = 10; emit(task, "agent.started", "بدأ الوكيل تحليل الهدف وبناء خطة التنفيذ"); await updatePersisted(task); await new Promise(resolve => setTimeout(resolve, 120));
    if (task.pauseRequested || shuttingDown) { task.status = "paused"; emit(task, "task.paused", "تم حفظ المهمة عند آخر نقطة آمنة"); }
    else { task.status = "running"; task.progress = 35; emit(task, "agent.step.started", "بدأ تنفيذ الخطوات المصرّح بها"); await updatePersisted(task); const result = await runAgent({ userId: task.userId, messages: task.messages }); if (task.pauseRequested || shuttingDown) { task.status = "paused"; emit(task, "task.paused", "تم إيقاف المهمة بعد آخر خطوة مكتملة"); } else { task.status = "completed"; task.progress = 100; task.result = result.assistant; emit(task, "task.completed", "اكتملت المهمة وتم التحقق من النتيجة", { provider: result.provider, toolEvents: result.toolEvents.length }); } }
  } catch (error) { task.retries += 1; task.lastError = error instanceof Error ? error.message : "Unknown task error"; if (task.attemptCount >= task.maxAttempts) { task.status = "dead_letter"; task.progress = 100; emit(task, "task.dead_letter", "نُقلت المهمة إلى dead-letter بعد استنفاد المحاولات", { maxAttempts: task.maxAttempts }); } else { task.status = "queued"; task.nextRetryAt = new Date(Date.now() + backoff(task.attemptCount)).toISOString(); task.progress = 15; emit(task, "task.retrying", `ستتم إعادة المحاولة بعد ${Math.round(backoff(task.attemptCount) / 1000)} ثانية`, { attempt: task.attemptCount, nextRetryAt: task.nextRetryAt }); } }
  finally { clearInterval(heartbeat); task.workerId = null; task.lockedAt = null; task.heartbeatAt = null; await updatePersisted(task); }
}
async function recoverExpired() { for (const task of Array.from(fallbackTasks.values())) { if (["planning", "running"].includes(task.status) && isLeaseExpired(task)) { task.status = "queued"; task.workerId = null; task.lockedAt = null; task.heartbeatAt = null; emit(task, "task.recovered", "استعيدت المهمة بعد انتهاء lease العامل"); await updatePersisted(task); } } }
async function hydratePersistedTasks() { const db = await getDb(); if (!db) return; const rows = await db.select().from(tasks).where(inArray(tasks.status, ["queued", "planning", "running"])).limit(100); for (const row of rows) { if (fallbackTasks.has(row.id)) continue; let messages: AgentMessage[] = []; try { messages = JSON.parse(row.messages) as AgentMessage[]; } catch { messages = [{ role: "user", content: row.goal }]; } const task: MemoryTask = { ...toSnapshot(row), messages, events: [] }; fallbackTasks.set(task.id, task); nextId = Math.max(nextId, task.id + 1); } }
async function drain() { if (workerActive || shuttingDown) return; workerActive = true; try { await recoverExpired(); for (const task of Array.from(fallbackTasks.values())) if (task.status === "queued") await execute(task); } finally { workerActive = false; } }
export function startTaskWorker() { if (workerTimer || process.env.NODE_ENV === "test") return; void hydratePersistedTasks().then(() => drain()).catch(error => console.error("[TaskWorker] hydration failed", error)); workerTimer = setInterval(() => void drain(), 5000); }
export async function shutdownTaskWorker() { shuttingDown = true; if (workerTimer) clearInterval(workerTimer); workerTimer = undefined; await drain(); }

export async function createTask(input: { userId: number; goal: string; messages: AgentMessage[]; idempotencyKey?: string }): Promise<TaskSnapshot> {
  const existing = input.idempotencyKey ? Array.from(fallbackTasks.values()).find(task => task.idempotencyKey === input.idempotencyKey && task.userId === input.userId) : undefined; if (existing) return snapshot(existing);
  const task: MemoryTask = { id: nextId++, userId: input.userId, goal: input.goal, messages: input.messages, status: "queued", progress: 0, retries: 0, attemptCount: 0, maxAttempts: 3, events: [], createdAt: now(), updatedAt: now(), idempotencyKey: input.idempotencyKey };
  fallbackTasks.set(task.id, task); const db = await getDb(); if (db) { const inserted = await db.insert(tasks).values({ userId: input.userId, goal: input.goal, messages: JSON.stringify(input.messages), status: "queued", progress: 0, retries: 0, attemptCount: 0, maxAttempts: 3, idempotencyKey: input.idempotencyKey ?? null }).catch(() => undefined); const insertedId = Number((inserted as any)?.[0]?.insertId ?? 0); if (insertedId > 0) { fallbackTasks.delete(task.id); task.id = insertedId; fallbackTasks.set(task.id, task); nextId = Math.max(nextId, insertedId + 1); } }
  emit(task, "task.created", "تم إنشاء مهمة قابلة للاستئناف"); if (process.env.NODE_ENV !== "test") void drain(); return snapshot(task);
}
export async function getTask(id: number): Promise<TaskSnapshot | undefined> { const local = getMemoryTask(id); if (local) return snapshot(local); const db = await getDb(); if (!db) return undefined; const row = (await db.select().from(tasks).where(eq(tasks.id, id)).limit(1))[0]; return row ? toSnapshot(row) : undefined; }
function toSnapshot(row: any): TaskSnapshot { return { id: row.id, userId: row.userId, goal: row.goal, status: row.status as TaskStatus, progress: row.progress, retries: row.retries, attemptCount: row.attemptCount ?? 0, maxAttempts: row.maxAttempts ?? 3, workerId: row.workerId, lockedAt: row.lockedAt?.toISOString() ?? null, heartbeatAt: row.heartbeatAt?.toISOString() ?? null, nextRetryAt: row.nextRetryAt?.toISOString() ?? null, result: row.result, lastError: row.lastError, createdAt: row.createdAt.toISOString(), updatedAt: row.updatedAt.toISOString() }; }
export async function listTasks(userId: number) { const local = Array.from(fallbackTasks.values()).filter(task => task.userId === userId).sort((a, b) => b.id - a.id).map(snapshot); if (local.length) return local; const db = await getDb(); if (!db) return []; const rows = await db.select().from(tasks).where(eq(tasks.userId, userId)).orderBy(desc(tasks.createdAt)).limit(50); return rows.map(toSnapshot); }
export async function pauseTask(id: number) { const task = getMemoryTask(id); if (!task || ["completed", "failed", "cancelled", "dead_letter"].includes(task.status)) return getTask(id); task.pauseRequested = true; task.status = "paused"; task.updatedAt = now(); emit(task, "task.paused", "طلب المستخدم إيقاف المهمة"); await updatePersisted(task); return snapshot(task); }
export async function resumeTask(id: number) { const task = getMemoryTask(id); if (!task || task.status !== "paused") return getTask(id); task.pauseRequested = false; task.status = "queued"; task.updatedAt = now(); emit(task, "task.resumed", "استُكملت المهمة من آخر نقطة آمنة"); if (process.env.NODE_ENV !== "test") void drain(); return snapshot(task); }
export async function cancelTask(id: number) { const task = getMemoryTask(id); if (!task) return getTask(id); task.status = "cancelled"; task.progress = 100; task.updatedAt = now(); emit(task, "task.cancelled", "أُلغيَت المهمة بناءً على طلب المستخدم"); await updatePersisted(task); return snapshot(task); }
export async function retryTask(id: number) { const task = getMemoryTask(id); if (!task || !["failed", "cancelled", "dead_letter"].includes(task.status)) return getTask(id); task.status = "queued"; task.progress = 0; task.lastError = null; task.retries = 0; task.attemptCount = 0; task.pauseRequested = false; emit(task, "task.queued", "أُعيدت المهمة إلى الطابور"); if (process.env.NODE_ENV !== "test") void drain(); return snapshot(task); }
export async function getTaskEvents(id: number) { const local = getMemoryTask(id); if (local?.events.length) return local.events; const db = await getDb(); if (!db) return local?.events ?? []; const rows = await db.select().from(taskEvents).where(eq(taskEvents.taskId, id)).orderBy(taskEvents.createdAt); return rows.map(row => ({ id: String(row.id), taskId: row.taskId, type: row.type, message: row.message, createdAt: row.createdAt.toISOString(), metadata: row.metadata ? JSON.parse(row.metadata) as Record<string, unknown> : undefined })); }
export function subscribeTask(id: number, listener: (event: TaskEvent) => void) { const key = `task:${id}`; eventBus.on(key, listener); return () => eventBus.off(key, listener); }
export async function requestApproval(input: { taskId: number; userId: number; toolName: string; action: string; riskLevel?: string; requiredPermission?: string; resourceScope?: string }) { const db = await getDb(); if (!db) return { id: `approval-${input.taskId}`, status: "pending" as const }; const result = await db.insert(approvals).values({ taskId: input.taskId, userId: input.userId, toolName: input.toolName, action: input.action, riskLevel: input.riskLevel ?? "high", requiredPermission: input.requiredPermission ?? null, resourceScope: input.resourceScope ?? null, status: "pending" }); return { id: String(result[0]?.insertId ?? input.taskId), status: "pending" as const }; }
export async function listApprovals(input: { taskId: number; userId: number }) { const db = await getDb(); if (!db) return []; return db.select().from(approvals).where(and(eq(approvals.taskId, input.taskId), eq(approvals.userId, input.userId))).orderBy(desc(approvals.createdAt)); }
export async function resolveApproval(input: { id: number; taskId: number; userId: number; status: "approved" | "rejected" }) { const db = await getDb(); if (!db) return { id: input.id, status: input.status }; await db.update(approvals).set({ status: input.status, resolvedAt: new Date() }).where(and(eq(approvals.id, input.id), eq(approvals.taskId, input.taskId), eq(approvals.userId, input.userId))); return { id: input.id, status: input.status }; }
